services:
  mysql:
    image: mysql:8.0
    container_name: todo_app_mysql_db

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: todo_app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
    networks:
      - todo_app_network

volumes:
  mysql_data:

networks:
  todo_app_network:
