#!/bin/bash

if test "$#" -ne 3; then
    echo "USAGE: HOST PORT USER"
    echo "Password can either be specified as an environment variable '\$PASSWORD' or through stdin"
    exit 1
fi

HOST="$1"
PORT="$2"
USER="$3"
if [[ -z ${PASSWORD+x} ]]; then
    read -p 'Password:' -s PASSWORD
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# MySQL connection strings
STMT_DB="-h$HOST -P$PORT -u$USER -p$PASSWORD"
CONFIG="-h$HOST -P$PORT -u$USER -p$PASSWORD todo_app"

# Check if database exists using MySQL commands
mysql $STMT_DB -e "SHOW DATABASES LIKE 'todo_app'" | grep 'todo_app' > /dev/null
if [[ $? = 0 ]]; then
    echo "NOTE: todo app db already exists, not going to create db"
else
    mysql $STMT_DB -e "CREATE DATABASE todo_app;"
fi


mysql $STMT_DB -c '\dn' | grep 'task' > /dev/null
if [[ $? = 0 ]]; then
    echo "NOTE: task schema already exists, not going to create schema"
else
    mysql $STMT_DB -f ${DIR}/schema.task.sql
fi

mysql $STMT_DB -f ${DIR}/seed.task.sql